CREATE TABLE IF NOT EXISTS "email_sms"(
    "id" UUID PRIMARY KEY,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "email" VARCHAR(128) NOT NULL,
    "otp" VARCHAR(6) DEFAULT ''::VARCHAR,
    "expires_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
